spring:
    activemq:
        in-memory: true
        broker-url: ${AMQ_URL:tcp://localhost:61616}
        user: ${AMQ_USER:admin}
        password: ${AMQ_PASSWORD:admin}

queue:
    name: ${QUEUE_NAME:queue-example}
    address: ${QUEUE_ADDRESS:}

logging:
    level:
        br.com.niwkleber: ${LOG_LEVEL:INFO}
